### ISSUE TITLE
提示需要验证码，请问如何解决？

### ISSUE THREAD

**Issue by jiji262** [huanz/wechat-mp-hack#1]
![snip20170220_2](https://cloud.githubusercontent.com/assets/168751/23116787/65881676-f787-11e6-9ff8-9367b6018a38.png)

**Comment by huanz** [comment]
@jiji262 我明天看下

**Comment by huanz** [comment]
@jiji262 哪个接口需要验证码？

**Comment by jiji262** [comment]
登录

**Comment by huanz** [comment]
@jiji262 验证码目前暂时无法处理，出验证码应该是你密码错误多次了

**Comment by jiji262** [comment]
并没有输入错误多次啊 
如何避免验证码出现？

**Comment by huanz** [comment]
@jiji262 你可以试下新版
