### ISSUE TITLE
创建图文消息的接口可以添加自动上传图片的功能吗？

### ISSUE THREAD

**Issue by elliotxx** [huanz/wechat-mp-hack#2]
如题，发现用operate_appmsg接口上传的图文消息只有文字。

**Comment by huanz** [comment]
本来就可以自动上传图片啊

**Comment by elliotxx** [comment]
为什么我试验的不可以 _(:з」∠)_
html中的图片链接给自动忽略了

**Comment by huanz** [comment]
@windcode 哦，html里面的图片确实没处理

**Comment by elliotxx** [comment]
那怎么能把图文消息里的图片一并自动上传呢？ 
正在用你的接口实现一个功能，卡在这里了 = =

**Comment by huanz** [comment]
@windcode 正在修这个问题

**Comment by elliotxx** [comment]
Nice！

**Comment by huanz** [comment]
@windcode npm下载最新版本再试

**Comment by elliotxx** [comment]
好的！
