### ISSUE TITLE
大家辛苦了！我想问一下安装问题

### ISSUE THREAD

**Issue by yan1zhao** [huanz/wechat-mp-hack#3]
您好！我在win7上安装了npm8.11。

在运行npm i wechat-mp-hack --save时，提示：
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie
https://nodesecurity.io/advisories/130 

npm WARN @1.0.0 No description
npm WARN @1.0.0 No repository field.

+ wechat-mp-hack@1.1.5
updated 1 package in 8.532s
这三个警告信息是可以忽略的吧。

我的问题是，const Wechat = require('wechat-mp-hack');
const API = new Wechat('公众号账号', '公众号密码');
这两行命令在哪个界面输入运行呢，我是小白，感谢大家的指点！

**Comment by huanz** [comment]
@yan1zhao 新建一个js文件，然后通过node运行
