### ISSUE TITLE
How to get create type=10 msg url?

### ISSUE THREAD

**Issue by inevity** [huanz/wechat-mp-hack#5]
I see code 
```
      return (0, _request4.default)({
            url: `${_config2.default.api.operate_appmsg}?t=ajax-response&sub=${appMsgId ? 'update' : 'create'}&type=10&token=${this.data.token}`,
            headers: {
                'Referer': `${_config2.default.api.appmsg}?t=media/appmsg_edit&action=edit&type=10&isMul=1&isNew=1&token=${this.data.token}`
            },
            form: params
```
When use puppeteer to create type10 msg,  should use ctrl +v to copy the html page into the editor.  But puppeteer does not support the keyboard comb. So resort to you .

**Comment by huanz** [comment]
@inevity When you paste in, the editor will process the content you paste.you can see [UEditor](https://ueditor.baidu.com/website/onlinedemo.html)
