### ISSUE TITLE
请问为什么在微信公众号取消了群发验证保护，仍然还需要扫描二维码才能群发呢？

### ISSUE THREAD

**Issue by basillee** [huanz/wechat-mp-hack#6]

**Comment by huanz** [comment]
@basillee 已经登录了么？截图看下控制台输出？

**Comment by basillee** [comment]
你好，问题我已经定位到了，在index.js 的 masssend方法中有：

**Comment by basillee** [comment]
你好，问题我已经定位到了，在index.js 的 masssend方法中有：
if (this.data.mass_protect) {
            return new Promise((resolve, reject) => {
                this.getticket().then(body => {
                    this.getuuid(body.ticket).then(uuid => {
                        this.checkuuid(uuid, body.ticket, body.operation_seq).then(res => {
                            params.operation_seq = body.operation_seq;
                            params.code = res.code;
                            this.safesend(params).then(resolve).catch(reject);
                        }).catch(reject);
                    }).catch(reject);
                }).catch(reject);
            });
        } else {
            params.operation_seq = this.data.operation_seq;
            return this.safesend(params);
        }

跟了一下，发现this.data.mass_protect 最终读取的是cache目录的缓存数据，删除缓存重新登录之后问题得到解决。
应该是我一开始使用的时候，微信后台是默认开启了验证保护，后面关闭了验证保护之后cache数据没有更新。

建议这里优化一下，每次重新登录之后，cache数据重新写一次。

另外大神，请问一下，这个登录的有效期多久呢？我服务器部署了定时任务，发现一天之后并没有群发消息，每天都需要扫码登录一次吗？

**Comment by basillee** [comment]
> 你好，问题我已经定位到了，在index.js 的 masssend方法中有：
> if (this.data.mass_protect) {
> return new Promise((resolve, reject) => {
> this.getticket().then(body => {
> this.getuuid(body.ticket).then(uuid => {
> this.checkuuid(uuid, body.ticket, body.operation_seq).then(res => {
> params.operation_seq = body.operation_seq;
> params.code = res.code;
> this.safesend(params).then(resolve).catch(reject);
> }).catch(reject);
> }).catch(reject);
> }).catch(reject);
> });
> } else {
> params.operation_seq = this.data.operation_seq;
> return this.safesend(params);
> }
> 
> 跟了一下，发现this.data.mass_protect 最终读取的是cache目录的缓存数据，删除缓存重新登录之后问题得到解决。
> 应该是我一开始使用的时候，微信后台是默认开启了验证保护，后面关闭了验证保护之后cache数据没有更新。
> 
> 建议这里优化一下，每次重新登录之后，cache数据重新写一次。
> 
> 另外大神，请问一下，这个登录的有效期多久呢？我服务器部署了定时任务，发现一天之后并没有群发消息，每天都需要扫码登录一次吗？

补充日志，原来的data数据为{"token":"2018xxxx11","ticket":"dc20fcxxxxxxxxxxxxxxxxxxxxx16f97aa3c39f","user_name":"xxxx_Lee","mass_protect":1}
删除缓存之后的data数据为
{"token":"64762xxx","ticket":"dc20fcxxxxxxxxxxxxxxxxxxxdd693e4xxxxxxx","user_name":"IT_Road_Lee"}

**Comment by huanz** [comment]
缓存了是否群发的信息，暂时不处理
