### ISSUE TITLE
群发消息接口报错

### ISSUE THREAD

**Issue by sky519** [huanz/wechat-mp-hack#8]
{"base_resp":{"err_msg":"default","ret":64007,"msg":"系统繁忙，请稍后重试"}}
请问大佬这是个什么错误？

**Comment by huanz** [comment]
微信的接口报错

**Comment by pensacola1989** [comment]
你好。试了好几个公众号都是这个报错。是微信屏蔽了相关调用么？

**Comment by pensacola1989** [comment]
你好。试了好几个公众号都是这个报错。是微信屏蔽了相关调用么？
