### ISSUE TITLE
关于长久保持登录态的问题

### ISSUE THREAD

**Issue by star7th** [huanz/wechat-mp-hack#9]
我觉得这个项目挺好玩的，已经用于实战，定时自动化推送一些内容集合。
但在长久地保持登录态这件事上，有点小麻烦。我本来是设置定时任务，每一个小时获取一次图文列表，希望这样起到心跳的作用，一直保持在线。但其实这种方法只能坚持一天就失效了。
所以我在想是不是出现互动类的操作更容易保持登录态。所以我就想，每小时“上传图文消息后再删除”，这样来保持登录态。不过目前项目似乎没有删除素材接口？如果不删除的话，会导致很多多余信息累积。

**Comment by huanz** [comment]
@star7th 已增加删除del_appmsg  其实通过operate_appmsg方法也可以，可以不断更新某个素材

**Comment by huanz** [comment]
保存登录这个暂时没时间细研究，不知道频繁操作是否可行， @star7th 你可以实验下，可行的话我可以抽时间加下，或者你提PR也可以~~~

**Comment by star7th** [comment]
实测即使一直更新素材也保持不了登录态。

**Comment by Norcy** [comment]
那要如何才能长期无人值守，自动定时群发消息呢？
